# Generated by Baton from roles.judge.council.
# Source council.skill: https://github.com/ParadoxZW/council.skill
# Append this file to council-def.sh only after reviewing the commands.

council-cc-opus() {
  env -u ANTHROPIC_BASE_URL -u ANTHROPIC_AUTH_TOKEN -u ANTHROPIC_API_KEY -u ANTHROPIC_MODEL -u OPENAI_BASE_URL -u OPENAI_API_KEY -u OPENAI_MODEL -u CLAUDISH_STATUSLINE_COMMAND -u CLAUDISH_STATUSLINE_REFRESH -u CLAUDE_CONFIG_DIR claude --model opus -p "$@"
}

council-codex-sol() {
  codex exec --sandbox read-only --skip-git-repo-check -m gpt-6.1-sol -c 'model_reasoning_effort="xhigh"' "$@"
}
