#!/usr/bin/env python3
"""Generate council.skill config and backend functions from Baton role config.

The generated shell is intentionally plain and sourceable by council.skill
(https://github.com/ParadoxZW/council.skill). Names and argument values are
validated/quoted before they become shell code.
"""
import argparse
import json
import os
import re
import shlex
from pathlib import Path


NAME_RE = re.compile(r"[A-Za-z0-9_-]+$")


def load(path):
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        data = {}
    roles = data.get("roles") if isinstance(data, dict) else {}
    judge = roles.get("judge") if isinstance(roles, dict) else {}
    judge = judge if isinstance(judge, dict) else {}
    council = judge.get("council") if isinstance(judge.get("council"), dict) else {}
    conductor = roles.get("conductor") if isinstance(roles, dict) else {}
    conductor = conductor if isinstance(conductor, dict) else {}
    chief_model = council.get("chief_model") or conductor.get("model") or conductor.get("label") or "claude"
    names = []
    members = []
    for item in council.get("councilors") or []:
        if not isinstance(item, dict):
            continue
        name = str(item.get("name") or "")
        if not NAME_RE.fullmatch(name):
            raise ValueError("councilor 名称只能包含字母、数字、下划线和短横线：{}".format(name))
        if name in names:
            continue
        names.append(name)
        members.append(item)
    return {"chief_model": chief_model, "chief_backend": council.get("chief_backend") or "", "councilors": names}, members


def shell_word(value):
    return shlex.quote(str(value))


def render(config, members):
    lines = [
        "# Generated by Baton from roles.judge.council.",
        "# Source council.skill: https://github.com/ParadoxZW/council.skill",
        "# Append this file to council-def.sh only after reviewing the commands.",
        "",
    ]
    for item in members:
        name = item["name"]
        adapter = str(item.get("adapter") or "claude").lower()
        model = item.get("model") or ""
        profile = item.get("profile") or ""
        command = item.get("command") or ("claude-all" if profile else "claude")
        if adapter == "codex":
            args = ["codex", "exec", "--sandbox", "read-only", "--skip-git-repo-check"]
            if model:
                args += ["-m", model]
            if item.get("reasoning_effort"):
                args += ["-c", 'model_reasoning_effort="{}"'.format(item["reasoning_effort"])]
            lines.append("{}() {{".format(name))
            lines.append("  {} \"$@\"".format(" ".join(shell_word(x) for x in args)))
            lines.append("}")
        else:
            try:
                args = shlex.split(str(command))
            except ValueError:
                args = [str(command)]
            command_name = os.path.basename(shlex.split(str(command))[0]) if str(command).split() else "claude"
            if command_name == "claude-all" and profile:
                args.append(profile)
            if model:
                args += ["--model", model]
            args.append("-p")
            lines.append("{}() {{".format(name))
            if command_name == "claude" and not item.get("inherit_env", False):
                unset = " ".join("-u {}".format(x) for x in (
                    "ANTHROPIC_BASE_URL", "ANTHROPIC_AUTH_TOKEN", "ANTHROPIC_API_KEY", "ANTHROPIC_MODEL",
                    "OPENAI_BASE_URL", "OPENAI_API_KEY", "OPENAI_MODEL", "CLAUDISH_STATUSLINE_COMMAND",
                    "CLAUDISH_STATUSLINE_REFRESH", "CLAUDE_CONFIG_DIR"))
                lines.append("  env {} {} \"$@\"".format(unset, " ".join(shell_word(x) for x in args)))
            else:
                lines.append("  {} \"$@\"".format(" ".join(shell_word(x) for x in args)))
            lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", required=True)
    ap.add_argument("--config-output", required=True)
    ap.add_argument("--def-output", required=True)
    args = ap.parse_args(argv)
    config, members = load(args.source)
    Path(args.config_output).write_text(json.dumps(config, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    Path(args.def_output).write_text(render(config, members), encoding="utf-8")
    print(" ".join(config["councilors"]))


if __name__ == "__main__":
    main()
